version: '3'
services:

  caddy:
    build:
      context: ..
      dockerfile: docker/proxy/Dockerfile
    environment:
      TOB_API_URL: ${TOB_API_URL:-}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
      WEB_HOST_NAME: ${WEB_HOST_NAME:-0.0.0.0}
      WEB_HOST_PORT: ${WEB_HOST_PORT:-8080}
      WEB_HOST_TLS: ${WEB_HOST_TLS:-off}
      AGENT_HOST: ${AGENT_HOST:-agent}
      AGENT_PORT: ${AGENT_PORT:-8000}
    links:
      - onbis-agent:agent
    networks:
      - vonx
    ports:
      - ${WEB_HTTP_PORT:-5000}:${WEB_HOST_PORT:-8080}
    volumes:
      - caddy-data:/root/.caddy
      - caddy-logs:/srv/logs

  onbis-agent:
    build:
      context: ..
      dockerfile: docker/agent/Dockerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL:-http://localhost:5000}
      CONFIG_ROOT: ../config
      ENVIRONMENT: ${ENVIRONMENT:-default}
      ENABLE_GUNICORN: ${ENABLE_GUNICORN:-0}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      PYTHON_ENV: ${PYTHON_ENV:-development}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_APP_URL: ${TOB_APP_URL:-}
      WALLET_SEED_ONBIS: ${WALLET_SEED_ONBIS:-}
    external_links:
       - tob_tob-api_1:tob-api
    networks:
      - orgbook
      - vonx
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - onbis-agent-wallet:/home/indy/.indy_client/wallet

volumes:
  caddy-data:
  caddy-logs:
  onbis-agent-wallet:

networks:
  vonx:
  orgbook:
    external:
      name: tob_tob
