issuers:
  ONBIS:
    path: /onbis

forms:
  onbis-incorp:
    path: /onbis/incorporation
    type: issue-credential
    schema_name: incorporation.onbis.gov.on.ca
    page_title: Ontario Registries
    title: Incorporation
    template: onbis.index.html
    description: >
      Ontario Registries and Online Services administers and supports the legal framework
      used for operating a business, not-for-profit society, cooperative association
      or financial institution in Ontario Organizations need to register, file documents
      and update records, which are kept as a matter of public record.
    explanation: Use the form below to register a Ontario corporation.

    js_includes:
      - src: js/onbis.js

    fields:
      - name: legal_name
        label: Legal Name
        type: text
        required: true

      - name: address
        label: Mailing Address
        type: address
        required: true

    mapping:
      attributes:
        - name: legal_entity_id
          from: helper
          source: uuid

        - name: corp_num
          from: previous
          source: legal_entity_id

        - name: org_type
          from: literal
          source: CO

        - name: effective_date
          from: helper
          source: now

        - name: end_date
          from: literal
          source: null

  onbis-dba:
    path: /onbis/dba
    type: issue-credential
    schema_name: doing_business_as.onbis.gov.on.ca
    page_title: Ontario Corporate Registry
    title: Doing Business As
    template: onbis.index.html
    description: >
      Ontario Registries and Online Services administers and supports the legal framework
      used for operating a business, not-for-profit society, cooperative association
      or financial institution in Ontario Organizations need to register, file documents
      and update records, which are kept as a matter of public record.
    explanation: Use the form below to add a Doing Business As name for your business.

    proof_request:
      name: registration
      params:
        source_id: org_id

    js_includes:
      - src: js/onbis.js

    hidden:
      - legal_entity_id

    fields:
      - name: doing_business_as_name
        label: Doing Business As Name
        type: text
        required: true

      - name: address
        label: Mailing Address
        type: address
        required: true

    mapping:
      attributes:
        - name: effective_date
          from: helper
          source: now

        - name: end_date
          from: literal
          source: null
