issuers:
  ONBIS:
    path: /onbis

forms:
  onbis-incorp:
    path: /onbis/registration
    type: issue-credential
    schema_name: registration.onbis.gov.on.ca
    page_title: Ontario Business Registries
    title: Registration
    template: onbis.index.html
    description: >
      Ontario Registries and Online Services administers and supports the legal framework
      used for operating a business, not-for-profit society, cooperative association
      or financial institution in Ontario Organizations need to register, file documents
      and update records, which are kept as a matter of public record.
    explanation: Use the form below to register a Ontario corporation.

    js_includes:
      - src: js/onbis.js

    fields:
      - name: business_name
        label: Business Name
        type: text
        required: true

      - name: address
        label: Business Address
        type: address
        required: true

    mapping:
      attributes:
        - name: business_number
          from: literal
          source: null

        - name: business_type
          from: literal
          source: CO

        - name: effective_date
          from: helper
          source: now

        - name: end_date
          from: literal
          source: null
