- name: registration.onbis.gov.on.ca
  version: '1.0.33'
  attributes:
    - business_number
    - associated_business
    - business_name
    - name_effective
    - business_status
    - status_effective
    - business_type
    - registered_jurisdiction
    - extra_provincial
    - home_jurisdiction
    - effective_date
    - end_date

- name: address.onbis.gov.on.ca
  version: '1.0.33'
  attributes:
    - business_number
    - addressee
    - address_type
    - civic_address
    - municipality
    - province
    - postal_code
    - country
    - effective_date
    - end_date
