- name: incorporation.onbis.gov.on.ca
  version: '1.0.33'
  attributes:
    - org_registry_id
    - associated_org
    - org_name
    - org_name_effective
    - org_name_trans
    - org_name_trans_effective
    - org_reg_status
    - org_status_effective
    - org_type
    - registered_jurisdiction
    - registration_type
    - home_jurisdiction
    - effective_date
    - end_date

- name: address.onbis.gov.on.ca
  version: '1.0.33'
  attributes:
    - org_registry_id
    - addressee
    - address_type
    - civic_address
    - municipality
    - province
    - postal_code
    - country
    - effective_date
    - end_date
