- name: incorporation.onbis.gov.on.ca
  version: '1.0.31'
  attributes:
    - company_number
    - associated_company
    - company_name
    - name_effective
    - company_status
    - status_effective
    - business_type
    - registered_jurisdiction
    - extra_provincial
    - home_jurisdiction
    - effective_date
    - end_date

- name: address.onbis.gov.on.ca
  version: '1.0.31'
  attributes:
    - company_number
    - associated_company
    - addressee
    - address_type
    - civic_address
    - municipality
    - province
    - postal_code
    - country
    - effective_date
    - end_date

- name: doing_business_as.onbis.gov.on.ca
  version: '1.0.31'
  attributes:
    - dba_number
    - corp_number
    - dba_name
    - name_effective
    - dba_status
    - status_effective
    - registered_jurisdiction
    - extra_provincial
    - home_jurisdiction
    - effective_date
    - end_date
