- name: registration.onbis.gov.on.ca
  version: '1.0.0'
  attributes:
    - registration_id
    - registration_date
    - registration_expiry_date
    - registration_renewal_effective
    - entity_name
    - entity_name_effective
    - entity_name_assumed
    - entity_name_assumed_effective
    - entity_name_trans
    - entity_name_trans_effective
    - entity_status
    - entity_status_effective
    - entity_type
    - registered_jurisdiction
    - extra_provincial_registration
    - home_jurisdiction
    - effective_date
 
- name: address.onbis.gov.on.ca
  version: '1.0.0'
  attributes:
    - registration_id
    - addressee
    - address_type
    - civic_address
    - municipality
    - province
    - postal_code
    - country
    - address_status
    - address_effective
    - effective_date
 
- name: relationship.onbis.gov.on.ca
  version: '1.0.0'
  attributes:
    - registration_id
    - associated_registration_id
    - relationship
    - relationship_description
    - relationship_status
    - relationship_status_effective
    - effective_date
 