issuers:
  ONBIS:
    name: Ontario Business Registries
    abbreviation: ONBIS
    email: onbis@ontario.ca
    url: $APPLICATION_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      seed: $WALLET_SEED_ONBIS

    credential_types:
      - description: Business Registration
        schema: incorporation.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_INCORP
        topic: 
          source_id:
            input: company_number
            from: claim
          type:
            input: incorporation
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: company_name
                from: claim
              type:
                input: company_name
                from: value
          - model: category
            fields:
              text:
                input: company_status
                from: claim
              type:
                input: topic_status
                from: value
            fields:
              text:
                input: business_type
                from: claim
              type:
                input: topic_type
                from: value

      - description: Doing Business As
        schema: doing_business_as.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_DBA
        topic: 
          parent_source_id:
            input: corp_number
            from: claim
          parent_type:
            input: incorporation
            from: value
          source_id:
            input: dba_number
            from: claim
          type:
            input: doing_business_as
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: dba_name
                from: claim
                processor:
                  - string_helpers.uppercase
              type:
                input: dba_name
                from: value
          - model: category
            fields:
              text:
                input: dba_status
                from: claim
              type:
                input: topic_status
                from: value

      - description: Registration Address
        schema: address.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_ADDRESS
        topic:
          -
            parent_source_id:
              input: associated_company
              from: claim
            parent_type:
              input: incorporation
              from: value
            source_id:
              input: company_number
              from: claim
            type:
              input: doing_business_as
              from: value
          -
            source_id:
              input: company_number
              from: claim
            type:
              input: incorporation
              from: value
        cardinality_fields:
          - address_type
        mapping:
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: civic_address
                from: claim
              city:
                input: municipality
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
              type:
                input: address_type
                from: claim
              effective_date:
                input: effective_date
                from: claim
              end_date:
                input: end_date
                from: claim
                
proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          name: incorporation.onbis.gov.on.ca
          version: '1.0.31'
        attributes:
          - company_number
          - company_name
          - business_type
          - addressee
          - local_address
          - municipality
          - province
          - postal_code
          - country
          - effective_date
          - end_date
