issuers:
  onbis:
    name: Ministry of Government and Consumer Services
    abbreviation: MGCS
    email: 393 University Avenue, Suite 200, Toronto, ON  M5G 2M2
    url: http://www.ontario.ca

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      seed: $WALLET_SEED_ONBIS

    credential_types:
      - description: Business Registration
        schema: registration.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_REGISTRATION
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: entity_name
                from: claim
              type:
                input: entity_name
                from: value
          - model: category
            fields:
              value:
                input: entity_status
                from: claim
              type:
                input: topic_status
                from: value
          - model: category
            fields:
              value:
                input: entity_type
                from: claim
              type:
                input: topic_type
                from: value

      - description: Business Address
        schema: address.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_ADDRESS
        topic:
          -
            source_id:
              input: registration_id
              from: claim
            type:
              input: registration
              from: value
        cardinality_fields:
          - address_type
        mapping:
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: civic_address
                from: claim
              city:
                input: municipality
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
              type:
                input: address_type
                from: claim
              effective_date:
                input: effective_date
                from: claim

      - description: Relationship
        schema: relationship.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_RELATIONSHIP
        topic:
          related_source_id:
            input: associated_registration_id
            from: claim
          related_type:
            input: registration
            from: value
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value

verifiers:
  ontob:
    name: ON OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false
    wallet:
      seed: "orgbook.von.gov.on.ca_dev_000000"

proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          name: registration.onbis.gov.on.ca
          version: '1.0.0'
        attributes:
