issuers:
  onbis:
    name: Ontario Business Registries
    abbreviation: ONBIS
    email: onbis@ontario.ca
    url: $APPLICATION_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      seed: $WALLET_SEED_ONBIS

    credential_types:
      - description: Business Registration
        schema: registration.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_INCORP
        topic: 
          parent_source_id:
            input: associated_business
            from: claim
          parent_type:
            input: registration
            from: value
          source_id:
            input: business_number
            from: claim
          type:
            input: registration
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: business_name
                from: claim
              type:
                input: business_name
                from: value
          - model: category
            fields:
              text:
                input: business_status
                from: claim
              type:
                input: topic_status
                from: value
            fields:
              text:
                input: business_type
                from: claim
              type:
                input: topic_type
                from: value

      - description: Business Address
        schema: address.onbis.gov.on.ca
        issuer_url: $APPLICATION_URL_ADDRESS
        topic:
          -
            parent_source_id:
              input: associated_business
              from: claim
            parent_type:
              input: registration
              from: value
            source_id:
              input: business_number
              from: claim
            type:
              input: registration
              from: value
        cardinality_fields:
          - address_type
        mapping:
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: civic_address
                from: claim
              city:
                input: municipality
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
              type:
                input: address_type
                from: claim
              effective_date:
                input: effective_date
                from: claim
              end_date:
                input: end_date
                from: claim
                
proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          name: registration.onbis.gov.on.ca
          version: '1.0.0'
        attributes:
          - business_number
          - business_name
          - business_type
          - civic_address
          - municipality
          - province
          - postal_code
          - country
          - effective_date
          - end_date
